using System;
using UnityEngine;
using UnityEngine.InputSystem;
using Zenject;

public class InputReader : IInputReader, IInitializable, IDisposable
{
    public float MoveValue { get; private set; }
    public event Action LaunchPerformed;

    private GameInputs _inputActions;

    public void Initialize()
    {
        _inputActions = new GameInputs();
        
        _inputActions.Player.Move.performed += ctx => MoveValue = ctx.ReadValue<float>();
        _inputActions.Player.Move.canceled += ctx => MoveValue = 0f;
        
        _inputActions.Player.Launch.performed += _ => LaunchPerformed?.Invoke();

        Enable();
    }

    public void Enable()
    {
        _inputActions?.Enable();
    }

    public void Disable()
    {
        _inputActions?.Disable();
    }

    public void Dispose()
    {
        _inputActions?.Dispose();
    }
}

// Mock of what Unity would generate from .inputactions to allow compilation
// In a real Unity project, this file would be generated by Unity.
// !!! REMOVE OR COMMENT THIS OUT IF YOU GENERATED THE C# CLASS IN UNITY !!!
/*
public class GameInputs : IDisposable
{
    public PlayerActions Player { get; }
    
    public GameInputs()
    {
        Player = new PlayerActions();
    }

    public void Enable() { }
    public void Disable() { }
    public void Dispose() { }

    public class PlayerActions
    {
        public InputAction Move { get; } = new InputAction("Move");
        public InputAction Launch { get; } = new InputAction("Launch");
    }
}
*/
